stages:
  - build_and_push
  - deploy

variables:
  DOCKER_IMAGE_PREFIX: "liubcheck/diploma"

build_and_push:
  stage: build_and_push
  image: docker:19.03.12
  services:
    - docker:dind
  before_script:
    - echo "Logging into Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Building and pushing eureka-server..."
    - docker build -t $DOCKER_IMAGE_PREFIX/eureka-server:latest ./eureka-server/
    - docker push $DOCKER_IMAGE_PREFIX/eureka-server:latest

    - echo "Building and pushing api-gateway..."
    - docker build -t $DOCKER_IMAGE_PREFIX/api-gateway:latest ./api-gateway/
    - docker push $DOCKER_IMAGE_PREFIX/api-gateway:latest

    - echo "Building and pushing lesson-service..."
    - docker build -t $DOCKER_IMAGE_PREFIX/lesson-service:latest ./lesson-service/
    - docker push $DOCKER_IMAGE_PREFIX/lesson-service:latest

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "Deploying services with Docker Compose..."
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
