stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - cd eureka-server && mvn clean package
    - cd ../api-gateway && mvn clean package
    - cd ../lesson-service && mvn clean package
    - cd ..
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/diploma/eureka-server:latest ./eureka-server/
    - docker push $DOCKER_USERNAME/diploma/eureka-server:latest
    - docker build -t $DOCKER_USERNAME/diploma/api-gateway:latest ./api-gateway/
    - docker push $DOCKER_USERNAME/diploma/api-gateway:latest
    - docker build -t $DOCKER_USERNAME/diploma/lesson-service:latest ./lesson-service/
    - docker push $DOCKER_USERNAME/diploma/lesson-service:latest
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker-compose up -d
  only:
    - main
