stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - cd eureka-server && mvn clean package
    - cd ../api-gateway && mvn clean package
    - cd ../lesson-service && mvn clean package
    - cd ..
    - sudo docker build -t diploma/eureka-server:prod ./eureka-server/
    - sudo docker build -t diploma/api-gateway:prod ./api-gateway/
    - sudo docker build -t diploma/lesson-service:prod ./analytic-service/
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker-compose up -d
  only:
    - main
