stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - eureka-server/target/*.jar
      - api-gateway/target/*.jar
      - lesson-service/target/*.jar
    expire_in: 1 hour

package:
  stage: package
  image: docker:19.03.12
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE_PREFIX/eureka-server:latest -f eureka-server/Dockerfile eureka-server/.
    - docker push $DOCKER_IMAGE_PREFIX/eureka-server:latest
    - docker build -t $DOCKER_IMAGE_PREFIX/eureka-server:latest -f api-gateway/Dockerfile api-gateway/.
    - docker push $DOCKER_IMAGE_PREFIX/api-gateway:latest
    - docker build -t $DOCKER_IMAGE_PREFIX/eureka-server:latest -f lesson-service/Dockerfile lesson-service/.
    - docker push $DOCKER_IMAGE_PREFIX/lesson-service:latest
  only:
    - main

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker-compose.deploy.yml up -d
  only:
    - main
