stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  tags:
    - deploy-diploma-be
  script:
    - cd eureka-server && mvn clean package
    - docker build -t registry.example.com/diploma/eureka-server:latest ./eureka-server/
    - docker push registry.example.com/diploma/eureka-server:latest

    - cd ../api-gateway && mvn clean package
    - docker build -t registry.example.com/diploma/api-gateway:latest ./api-gateway/
    - docker push registry.example.com/diploma/api-gateway:latest

    - cd ../lesson-service && mvn clean package
    - docker build -t registry.example.com/diploma/lesson-service:latest ./lesson-service/
    - docker push registry.example.com/diploma/lesson-service:latest
  artifacts:
    paths:
      - eureka-server/target/*.jar
      - api-gateway/target/*.jar
      - lesson-service/target/*.jar
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose up -d
  only:
    - main
