stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - eureka-server/target/*.jar
      - api-gateway/target/*.jar
      - lesson-service/target/*.jar

package:
  stage: package
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/diploma:eureka-server-prod ./eureka-server/
    - docker push $DOCKER_USERNAME/diploma:eureka-server-prod
    - docker build -t $DOCKER_USERNAME/diploma:api-gateway-prod ./api-gateway/
    - docker push $DOCKER_USERNAME/diploma:api-gateway-prod
    - docker build -t $DOCKER_USERNAME/diploma:lesson-service-prod ./lesson-service/
    - docker push $DOCKER_USERNAME/diploma:lesson-service-prod
  only:
    - main

deploy:
  stage: deploy
  image: docker:19.03.12
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - main
