stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-11
  tags:
    - deploy-diploma-be
  script:
    - mvn clean package
    - sudo docker build -t diploma/eureka-server ./eureka-server/
    - sudo docker build -t diploma/api-gateway ./api-gateway/
    - sudo docker build -t diploma/lesson-service ./lesson-service/
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - sudo docker compose up -d
  only:
    - main
    