stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  tags:
    - deploy-diploma-be
  script:
    - cd eureka-server && mvn clean package
    - cd ../api-gateway && mvn clean package
    - cd ../lesson-service && mvn clean package
    - cd ..
    - sudo docker build -t liubcheck/diploma/eureka-server:latest ./eureka-server/
    - sudo docker build -t liubcheck/diploma/api-gateway:latest ./api-gateway/
    - sudo docker build -t liubcheck/diploma/lesson-service:latest ./lesson-service/
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker-compose up -d
  only:
    - main
