stages:
  - build
  - deploy

build:
  stage: build
  image: docker:19.03
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_USERNAME/diploma/eureka-server ./eureka-server/
    - docker build -t $DOCKER_USERNAME/diploma/api-gateway ./api-gateway/
    - docker build -t $DOCKER_USERNAME/diploma/lesson-service ./lesson-service/
    - docker push $DOCKER_USERNAME/diploma/eureka-server
    - docker push $DOCKER_USERNAME/diploma/api-gateway
    - docker push $DOCKER_USERNAME/diploma/lesson-service
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose up -d
  only:
    - main
