version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  eureka-server:
    image: liubcheck/eureka-server:latest
    ports:
      - "8761:8761"

  api-gateway:
    image: liubcheck/api-gateway:latest
    depends_on:
      - eureka-server
    ports:
      - "9090:9090"

  lesson-service:
    image: liubcheck/lesson-service:latest
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db/diploma
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"

volumes:
  pgdata:
