name: Deploy Microservices to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          services=("eureka-server" "api-gateway" "lesson-service")
          for service in "${services[@]}"; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/diploma:$service-prod ./$service
            docker push ${{ secrets.DOCKER_USERNAME }}/diploma:$service-prod
          done

      - name: Deploy to Render - Eureka Server
        uses: renderinc/deploy-action@v1
        with:
          service_id: ${{ secrets.RENDER_EUREKA_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_SERVICE_API_KEY }}

      - name: Deploy to Render - API Gateway
        uses: renderinc/deploy-action@v1
        with:
          service_id: ${{ secrets.RENDER_API_GATEWAY_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_SERVICE_API_KEY }}

      - name: Deploy to Render - Lesson Service
        uses: renderinc/deploy-action@v1
        with:
          service_id: ${{ secrets.RENDER_LESSON_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_SERVICE_API_KEY }}
